name: Continuous Delivery - Nginx Pull & Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Nginx Container
    runs-on: self-hosted   # 👈 Runs on your VM runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: list folder in linux
        run: |
          echo "Listing files in the current directory..."
          ls -la

      - name: Pull latest Nginx image
        run: |
          echo "Pulling latest Nginx image..."
          docker pull nginx:latest

      - name: Deploy Nginx with Docker Compose
        run: |
          echo "Deploying Nginx..."
          docker compose -f docker-compose.yml up -d
