name: Deploy Vue.js App

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy to self-hosted server
    runs-on: self-hosted   # 🔥 Your server runner
    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v5

      # 2️⃣ Set up Docker (in case your runner needs it)
      - name: Set up Docker
        uses: docker/setup-buildx-action@v4

      # 3️⃣ Build Docker image
      - name: Build Docker image
        run: |
          docker build -t my-vue-app:latest ./github-action-tetst

      # 4️⃣ (Optional) Use Docker Compose for multi-container apps
      - name: Deploy with Docker Compose
        run: |
          docker compose down
          docker compose up -d --build

      # 5️⃣ (Optional) Clean up old images
      - name: Cleanup old images
        run: |
          docker image prune -f
